### ISSUE TITLE
custom the url for download

### ISSUE THREAD

**Issue by SolarisYan** [gliderlabs/herokuish#112]
how can i set the url for download?
ex: i want to deploy a node app,when i use the cmd:
docker run --rm -e TRACE=true -v /root/nodejs-flynn-example:/tmp/app gliderlabs/herokuish /bin/herokuish test
it alwalys fail to download the node-v0.10.42-linux-x64.tar.gz from the url :http://s3pository.heroku.com/node/v0.10.42/node-v0.10.42-linux-x64.tar.gz

i want to set the url ,but how?

the logs:

::: BUILDING APP :::
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  0.10.x
       engines.npm (package.json):   2.x
       
       Resolving node version 0.10.x via semver.io...
       Downloading and installing node 0.10.42...
       Unable to download node 0.10.42; does it exist?
     
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku

**Comment by michaelshobbs** [comment]
I'm not sure you can fully customize that URL. 

A few things to try:
1. Try downloading that URL manually to verify its existence 
2. Change the node/npm versions in package.json to something more recent. Is that version still available for download?
3. Pass `-e BUILDPACK_URL=<url-to-buildpack-repo>` in order to use the latest buildpack version. Perhaps they moved the file repo and updated the reference in a new buildpack version

**Comment by josegonzalez** [comment]
Since we use the upstream heroku buildpack for it, I think you'd need to fork the buildpack to add that functionality.

**Comment by SolarisYan** [comment]
@josegonzalez yes, i had,thx
