### ISSUE TITLE
buildback not included in slug, wrong path ?

### ISSUE THREAD

**Issue by OwlyCode** [gliderlabs/herokuish#24]
Hello,

I was playing with herokuish and stumbled upon this : 

When mounting a volume with my app in `/tmp/app` and doing this in the container : 

```bash
/bin/herokuish buildpack build
/bin/herokuish slug generate
```

Then the slug I get in /tmp/slug.tgz is the source as imported in `/tmp/app` and not the app I just built in `/app`.

**Comment by progrium** [comment]
Ah, took me a while to see what you meant and what could be happening. It does the import on every run, so `slug generate` would overwrite the result of the build. It should not import if APP_PATH is not empty. Okay, that's a bug. Sorry, importing is new.

**Comment by michaelshobbs** [comment]
This looks to be addressed [here](https://github.com/gliderlabs/herokuish/blob/019888cb6f0634a3ef8f8765c88070de1cef7c11/include/slug.bash#L8-L9)?

**Comment by matthewmueller** [comment]
Actually it looks like this is still happening. @OwlyCode explained it well, but it's a bit subtle because of the naming. To make it a bit simpler to follow, I'll use the node.js build process: 

1. `/bin/herokuish buildpack build` builds the app from `/tmp/app` into `/app` For node.js, `/app` would include things like the node_modules built for linux. These are not present in `/tmp/app`

2. Next, running `/bin/herokuish slug generate` generates a `.tar.gz` file from `/tmp/app` and not `/app`, so you end up with no node_modules.

It seems like the paths are right, this is what I'm seeing:

```
APP_PATH=/app                    # Application path during runtime
ENV_PATH=/tmp/env                # Path to files for defining base environment
BUILD_PATH=/tmp/build            # Working directory during builds
CACHE_PATH=/tmp/cache            # Buildpack cache location
IMPORT_PATH=/tmp/app             # Mounted path to copy to app path
BUILDPACK_PATH=/tmp/buildpacks   # Path to installed buildpacks
```

So it's a bit unclear to me how things are going awry. It seems like a small bug and I'll open a PR if i find the solution, but any direction from those more familiar with the codebase would be much appreciated!

**Comment by josegonzalez** [comment]
Mind filling a new issue?

**Comment by matthewmueller** [comment]
@josegonzalez done :-) https://github.com/gliderlabs/herokuish/issues/402

FWIW, It's not blocking me anymore. I actually kind of like the explicitness of the command I posted above, it allows me to exclude certain files from the tarball.
