### ISSUE TITLE
/tmp is way too small

### ISSUE THREAD

**Issue by guss77** [gliderlabs/herokuish#29]
Depending on your setup /tmp may be mounted on a really small tmpfs (I think this depends on the operating system, but on Fedora 22 this is 64MB), which if not enough for herokuish to deploy real applications.

The problem is that herokuish is using /tmp/build as a temporary "build area" and when deploying application composed of multiple git repositories, this will quickly fill up the small RAM disk mounted /tmp.

For now I'm using a workaround - by designating /tmp as a volume, it gets allocated a docker FS layer of itself, which allows /tmp to be the size of available space on the drive where docker stores its file system layers:

    docker run --rm -v /abs/app/path:/tmp/app -v /tmp gliderlabs/herokuish /bin/herokuish test

**Comment by mgood** [comment]
Can you provide some more details on the issue you encountered? How did you confirm that /tmp in the container is also mounted on a tmpfs?

Based on a quick look at containers on my local CoreOS and Boot2docker VMs, they don't mount a separate filesystem for "/tmp", so it will be stored within the Docker container's root filesystem (e.g. aufs, overlay, etc.)

Is there something in the default Docker configuration on Fedora that would override this to mount "/tmp" differently?

**Comment by guss77** [comment]
To check the file systems mounted, I've simply ran the gliderlabs/herokuish image with 'bash' as the command. The /tmp issue may be because Fedora by default /tmp is mounted on tmpfs.

**Comment by mgood** [comment]
So, the quick solution is you can override the environment variables here to use a location other than `/tmp`: https://github.com/gliderlabs/herokuish#paths

Mounting a volume for `/tmp` does give you more space, but the directory will be left on the host when the container exits, and you would need to manually clean it up. There are paths like `/tmp/cache` you may want to mount, in order to preserve the buildpack cache between builds, though `/tmp/build` looks like it's just a scratch directory for the build, that you probably want destroyed when the container exits.

I ran a Fedora 21 VM to take a look, and I see the same thing with `/tmp` on `tmpfs` inside the container, though I can't find any explicit configuration for that, and didn't find documentation of the behavior. I assume it's something built into the DeviceMapper driver's defaults, but I wasn't finding any details on it.

**Comment by guss77** [comment]
If I try to use `-e` to override the `BUILD_PATH`, the test fails:

~~~
$ docker run --rm -v $(pwd):/tmp/app -e BUILD_PATH=/mnt gliderlabs/herokuish /bin/herokuish test
::: BUILDING APP :::
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-multi/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-clojure/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-go/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-gradle/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-grails/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-java/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-multi/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-nodejs/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-php/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-play/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-python/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-ruby/bin/detect: access denied
setuidgid: fatal: unable to run /tmp/buildpacks/heroku-buildpack-scala/bin/detect: access denied
-----> Unable to select a buildpack
~~~

**Comment by michaelshobbs** [comment]
Is there something to do here for herokuish specifically?
