### ISSUE TITLE
FR: Respect .slugignore even when not using `slug` command

### ISSUE THREAD

**Issue by aleclarson** [gliderlabs/herokuish#291]
As a user of `coffee-script`, I like keeping the .js files out of git (using `.gitignore`), but want them on my dokku server. Similarly, I want the .coffee files in git, but off my dokku server.

So I have two needs here:
- Disable `.gitignore` when pushing to dokku
- Apply `.slugignore` in its place

I need some guidance on how to do the first bullet.
The second bullet can be done with a predeploy script, but I would prefer something easier.

**Comment by aleclarson** [comment]
Hmm, looks like I'll need a script that wraps around `git push` if I want to disable `.gitignore`.

So I might as well just replace the contents of `.gitignore` with what I have in `.slugignore`

**Comment by josegonzalez** [comment]
Note: herokuish supports slugignore when building slugs, but Dokku does not use slugs so doesn't have that functionality. TlAs I said in chat, this isn't something that is missing in herokuish but in Dokku.

**Comment by aleclarson** [comment]
Oh, I forgot that `herokuish` is just a dokku plugin and has no control over the `git push` behavior.

It just *feels* like a `herouish` feature because `.slugignore` is a Heroku thing.

Either way, I don't think Dokku can do anything about `.gitignore` preventing the .js files from being pushed to the Dokku server.

**Comment by josegonzalez** [comment]
As I said before, this is a Herokuish feature. Heroku supports `.slugignore` files when build slugs. If you build a Herokuish slug, you get this functionality.

Herokuish is not a Dokku plugin. It is a standalone project that is released as a docker image. This docker image contains the `herokuish` binary and helper binaries, which can be used to build heroku-compatible slugs and docker images.

Dokku doesn't use that functionality, and instead uses the resulting Herokuish image to trigger buildpacks and run the resulting docker image. That is why even though Dokku uses Herokuish, we don't get the `.slugignore` functionality because we don't even use slugs.
